[package]

name = "cowrc"
version = "0.0.4"
authors = ["Ty Overby <ty@pre-alpha.com>"]
license = "MIT"
description = "A set of copy-on-write smart pointers."

repository = "https://github.com/TyOverby/cowrc"
